robot_link_radius: 0.05
sample_states: [[0.13,-1.21,0.91,1.09,-2.19,1.33,-1.2,-1.82],
                [0.16,-0.99,1.09,2,-1.2,1.65,1.76,1.21],
                [0.01,-0.30,1.32,0.06,-2.01,-2.53,1.94,-0.84],
                [0.19,-0.72,-0.68,0.31,1.68,2.89,-1.14,-0.74],
                [0.1,-1.42,0.85,0.75,-1.37,-3,-0.78,-0.82],
                [0.38,-0.83,1.08,-2.73,-1.47,-2.16,1.17,1.51],
                [0.08,-0.27,-0.49,-1.24,1.51,0.64,1.98,-1.06],
                [0.04,0.38,1.51,0.66,-2.25,2.97,-2.16,0.18],
                [0.21,0.31,1.39,-1.8,1.27,-0.13,1.89,2.72] ]
training_states:
problem_states:
boxes:
ellipsoids:
capsules:
cylinders:
